[tool.poetry]
name = "foundry_backend"
version = "0.1.0"
description = "The backend component of Foundry MLS"
authors = ["Will Boyd <will.boyd@abwlabs.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.2"

[tool.poetry.dev-dependencies]
pytest = "^5.1"
pytest-cov = "^2.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
