from django.db import models
import uuid


def generate_unique_mls(cls: models.Model) -> str:
    """
    Generate a unique MLS number for a realtor

    MLS numbers are generated by creating a unique UUID v4 object
    and taking the "node" section (last 6 bytes).

    :param cls: the class to check the MLS numbers for
    :return: a string ID, unique across cls.number
    """
    mls = uuid.uuid4()

    while cls.objects.filter(number=mls.fields[-1]).exists():
        mls = uuid.uuid4()

    return mls.fields[-1]
