apiVersion: v1
kind: Pod
spec:
  containers:
  - name: python3
    image: deploy.abwlabs.com/jenkins-python-builder:0.5.0
    command:
    - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  imagePullSecrets:
  - name: regcred
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: docker-registry-credentials
          items:
            - key: config.json
              path: config.json