# Generated by Django 2.2.5 on 2019-10-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IAMPolicyStatementConditionItem',
            new_name='IAMPolicyStatementCondition',
        ),
    ]
