# Generated by Django 2.2.5 on 2019-10-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iampolicy',
            name='name',
        ),
    ]
