# Generated by Django 2.2.5 on 2019-10-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191023_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iampolicystatementcondition',
            old_name='policy',
            new_name='statement',
        ),
    ]
