# Generated by Django 2.2.5 on 2019-10-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_iampolicy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='iampolicy',
            name='name',
            field=models.CharField(default='TESTTESTTEST', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
