# Generated by Django 2.2.5 on 2019-10-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_iampolicy_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iampolicyrule',
            old_name='list',
            new_name='policy',
        ),
    ]
