# Generated by Django 2.2.5 on 2019-10-27 05:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191023_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iampolicystatement',
            name='actions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('list', 'List all objects (GET)'), ('retrieve', 'Retrieve a specific object (GET with PK)'), ('create', 'Create a new object (POST)'), ('update', "Update a specific object in it's entirety (PUT)"), ('partial_update', "Update a specific object's specific elements (PATCH)"), ('delete', 'Delete an object (DELETE)'), ('all', 'All actions'), ('safe', 'Read only actions')], max_length=58),
        ),
    ]
