# Generated by Django 2.2.5 on 2019-09-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.TextField(unique=True),
        ),
    ]
