# Generated by Django 2.2.5 on 2019-10-12 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_code', models.CharField(max_length=50)),
                ('disarm_code', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.Property')),
            ],
        ),
    ]
