# Generated by Django 2.2.5 on 2019-10-18 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_homealarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.MLSNumber')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Listing')),
            ],
        ),
    ]
