# Generated by Django 2.2.5 on 2019-09-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190925_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLSNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SlugField(max_length=12, unique=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Agency')),
            ],
        ),
    ]
