# Generated by Django 2.2.5 on 2019-09-26 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0003_mlsnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlsnumber',
            name='number',
            field=models.SlugField(blank=True, max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mls', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.MLSNumber')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
