# Generated by Django 2.2.5 on 2019-09-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190926_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlsnumber',
            name='number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
