# Generated by Django 2.2.5 on 2019-10-24 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20191024_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyattraction',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='nearby_attractions', through='database.NearbyAttractionPropertyConnector', to='database.Property'),
        ),
        migrations.AlterField(
            model_name='room',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='database.Property'),
        ),
    ]
