# Generated by Django 2.2.5 on 2019-10-27 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20191024_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyattraction',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nearby_attractions', to='database.Property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nearbyattraction',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='nearbyattraction',
            unique_together={('property', 'name')},
        ),
        migrations.RemoveField(
            model_name='nearbyattraction',
            name='properties',
        ),
        migrations.DeleteModel(
            name='NearbyAttractionPropertyConnector',
        ),
    ]
