# Generated by Django 2.2.5 on 2019-10-27 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20191027_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyattraction',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='nearbyattraction',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='NearbyAttractionPropertyConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.NearbyAttraction')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Property')),
            ],
            options={
                'unique_together': {('attraction', 'property')},
            },
        ),
        migrations.RemoveField(
            model_name='nearbyattraction',
            name='property',
        ),
        migrations.AddField(
            model_name='nearbyattraction',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='nearby_attractions', through='database.NearbyAttractionPropertyConnector', to='database.Property'),
        ),
    ]
