# Generated by Django 2.2.5 on 2019-10-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20191027_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='database.Listing'),
        ),
    ]
