# Generated by Django 2.2.5 on 2019-10-04 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_property_schooldistrict_shoppingarea_subdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyAttraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('SCHOOL', 'School Zone'), ('SHOPS', 'Shopping Area'), ('NEIGHBORHOOD', 'Neighborhood')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='NearbyAttractionPropertyConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.NearbyAttraction')),
            ],
        ),
        migrations.DeleteModel(
            name='SchoolDistrict',
        ),
        migrations.DeleteModel(
            name='ShoppingArea',
        ),
        migrations.RemoveField(
            model_name='property',
            name='subdivision',
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('CONDO', 'Condominium'), ('DUPLEX', 'Duplex Home'), ('House', 'Standalone House')], default='HOUSE', max_length=12),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subdivision',
        ),
        migrations.AddField(
            model_name='nearbyattractionpropertyconnector',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Property'),
        ),
        migrations.AlterUniqueTogether(
            name='nearbyattractionpropertyconnector',
            unique_together={('attraction', 'property')},
        ),
    ]
