# Generated by Django 2.2.5 on 2019-10-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20191004_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('CONDO', 'Condominium'), ('DUPLEX', 'Duplex Home'), ('HOUSE', 'Standalone House')], max_length=12),
        ),
    ]
