# Generated by Django 2.2.5 on 2019-11-08 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20191106_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Address'),
        ),
    ]
