# Generated by Django 2.2.5 on 2019-11-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20191108_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('BEDROOM', 'Bedroom'), ('BATHROOM', 'Bathroom'), ('HALF_BATHROOM', '1/2 bathroom'), ('KITCHEN', 'Kitchen'), ('DINING', 'Dining Room'), ('OFFICE', 'Office'), ('DEN', 'Den'), ('LIVING', 'Living Room'), ('FAMILY', 'Family Room'), ('GARAGE', 'Garage'), ('CAR_PORT', 'Car Port'), ('RECREATION', 'Recreational Room')], max_length=15),
        ),
    ]
