# Generated by Django 2.2.5 on 2019-10-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20191004_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyattraction',
            name='type',
            field=models.CharField(choices=[('SCHOOL_ELEM', 'Public Elementary School'), ('SCHOOL_MIDDLE', 'Public Middle School'), ('SCHOOL_HIGH', 'Public High School'), ('SCHOOL_PRIVATE', 'Private School'), ('SHOPS', 'Shopping Area'), ('NEIGHBORHOOD', 'Neighborhood')], max_length=15),
        ),
    ]
