# Generated by Django 2.2.5 on 2019-11-17 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20191116_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='acreage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)]),
            preserve_default=False,
        ),
    ]
