# Generated by Django 2.2.5 on 2019-10-06 03:32

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20191004_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyattraction',
            name='type',
            field=models.CharField(choices=[('SCHOOL_ELEM', 'Public Elementary School'), ('SCHOOL_MIDDLE', 'Public Middle School'), ('SCHOOL_HIGH', 'Public High School'), ('SCHOOL_PRIVATE', 'Private School'), ('SHOPPING', 'Shopping Area'), ('NEIGHBORHOOD', 'Neighborhood'), ('ENTERTAINMENT', 'Entertainment Area')], max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
