# Generated by Django 2.2.5 on 2019-10-06 17:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20191006_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(5)])),
                ('state', models.CharField(max_length=15)),
                ('state_code', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)])),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Address'),
        ),
    ]
