# Generated by Django 2.2.5 on 2019-11-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_listingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlsnumber',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ListingImage',
        ),
    ]
