# Generated by Django 2.2.5 on 2019-11-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingsHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='database.Listing')),
            ],
        ),
    ]
