# Generated by Django 2.2.5 on 2019-11-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_listingshit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
