# Generated by Django 2.2.5 on 2019-11-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_usermessage_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearbyattraction',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
