# Generated by Django 2.2.5 on 2019-11-21 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20191120_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowingReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_interest', models.CharField(choices=[('LOW', 'Low Interest'), ('MEDIUM', 'Medium Interest'), ('HIGH', 'High Interest')], max_length=10)),
                ('overall_experience', models.CharField(choices=[('VERYPOOR', 'Very Poor Experience'), ('POOR', 'Poor Experience'), ('NEUTRAL', 'Neutral Experience'), ('GOOD', 'Good experience'), ('VERYGOOD', 'Very Good Experience')], max_length=10)),
                ('price_opinion', models.CharField(choices=[('LOW', 'Price is too low'), ('FAIR', 'Price is fair'), ('HIGH', 'Price is too high')], max_length=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showing_reviews', to='database.MLSNumber')),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='database.MLSNumber')),
            ],
        ),
    ]
