# Generated by Django 2.2.5 on 2019-12-05 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20191123_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='square_footage',
            field=models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
