# settings.yaml
# Foundry Backend
#
# This file defines the default settings to use for Foundry's Backend Server.
# This file has several sections:
# 1. default: The default configuration to use, if nothing else is specified
# 2. development, staging, production, and testing: Specific environments. These can be selected, at runtime, with the
#    FOUNDRY_ENV environment variable. Values here override values set in default
# 3. global: Values universal to all configuration. Values here override all other values.
#
# Values defined in this config file are only overridden by environment variables set at runtime
default:
  # The secret to use with CSFR.
  # NEVER USE THIS VALUE IN PRODUCTION. SEE https://www.miniwebtool.com/django-secret-key-generator/
  SECRET_KEY: 1234

  # The URL to host static content from
  STATIC_URL: /static/

  # Whether to run the server in debug mode.
  # https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-DEBUG
  DEBUG: false

  # Valid hosts to request from.
  # Change this in production
  ALLOWED_HOSTS:
    - '*'

  # Database
  # https://docs.djangoproject.com/en/2.0/ref/settings/#databases
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db.sqlite3

  # Valid Accept-Language HTTP Header
  LANGUAGE_CODE: en-us

  # A Valid UTC Time Zone Code
  TIME_ZONE: UTC

  # Use django's translation framework
  USE_I18N: true

  # Use locale data to format numbers and dates
  USE_L10N: true

  # Use Timezone-aware dates. See TIME_ZONE for zone to use
  USE_TZ: true

  # Valid django apps. Don't change unless you know what you're doing
  INSTALLED_APPS:
    - django.contrib.admin
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.messages
    - django.contrib.staticfiles
    - foundry_backend.database
    - rest_framework
    - phonenumber_field
    - address

  # Valid django middleware. Don't change unless you know what you're doing
  MIDDLEWARE:
    - django.middleware.security.SecurityMiddleware
    - django.contrib.sessions.middleware.SessionMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.contrib.auth.middleware.AuthenticationMiddleware
    - django.contrib.messages.middleware.MessageMiddleware
    - django.middleware.clickjacking.XFrameOptionsMiddleware

  # Django's central urlconf. Don't change unless you know what you're doing
  ROOT_URLCONF: foundry_backend.urls

  # The module with the wsgi application. Don't change unless you know what you're doing
  WSGI_APPLICATION: foundry_backend.wsgi.application

  # The Django Template Config. Don't change unless you know what you're doing
  TEMPLATES:
    - BACKEND: django.template.backends.django.DjangoTemplates
      DIRS: []
      APP_DIRS: true
      OPTIONS:
        context_processors:
          - django.template.context_processors.debug
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
          - django.contrib.messages.context_processors.messages

  # Password validation
  # https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
  AUTH_PASSWORD_VALIDATORS:
    - NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
    - NAME: django.contrib.auth.password_validation.MinimumLengthValidator
    - NAME: django.contrib.auth.password_validation.CommonPasswordValidator
    - NAME: django.contrib.auth.password_validation.NumericPasswordValidator

development:
  DEBUG: true
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db.sqlite3

production:
  server: prodserver.com
  username: prod user
  foo: bar prod
  value: this value is for django app

staging:
  server: stagingserver.com
  username: staging user
  foo: bar stag

testing:
  server: stagingserver.com
  username: testing user
  foo: bar testing

global:
  foo: It overrides every other env